"use client";

import Image from "next/image";
import { ChevronLeft, ChevronRight, Expand, Images, LoaderCircle, RotateCcw, X } from "lucide-react";
import { createPortal } from "react-dom";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { PointerEvent as ReactPointerEvent } from "react";
import type { GalleryPagination, SerializedGalleryImage } from "@/lib/gallery-image-repository";

type PublicItem = Pick<SerializedGalleryImage, "id" | "url" | "alt" | "description" | "code" | "service" | "sortOrder" | "width" | "height">;
type Filter = "ALL" | PublicItem["service"];
type PublicResponse = { ok: true; images: PublicItem[]; pagination: GalleryPagination; message?: string };
const filters: { value: Filter; label: string }[] = [
  { value: "ALL", label: "All work" }, { value: "BESPOKE_SOFA", label: "Bespoke sofas" },
  { value: "COMMERCIAL_SOFA", label: "Commercial" }, { value: "INTERIOR_DESIGN", label: "Interiors" },
  { value: "SOFA_REPAIR_RESTORATION", label: "Restoration" },
];
const serviceLabel = Object.fromEntries(filters.slice(1).map((item) => [item.value, item.label])) as Record<PublicItem["service"], string>;

export default function GallerySection({ initialItems, initialPagination }: { initialItems: PublicItem[]; initialPagination: GalleryPagination }) {
  const [filter, setFilter] = useState<Filter>("ALL");
  const [items, setItems] = useState(initialItems);
  const [pageInfo, setPageInfo] = useState(initialPagination);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [loading, setLoading] = useState(false); const [filterLoading, setFilterLoading] = useState(false); const [error, setError] = useState("");
  const openerRef = useRef<HTMLButtonElement | null>(null); const sentinelRef = useRef<HTMLDivElement>(null);
  const requestRef = useRef(0); const abortRef = useRef<AbortController | null>(null); const loadingRef = useRef(false);
  const selectedIndex = useMemo(() => items.findIndex((item) => item.id === selectedId), [items, selectedId]);

  const fetchPage = useCallback(async (page: number, service: Filter, replace = false) => {
    if (loadingRef.current && !replace) return null;
    const requestId = ++requestRef.current; abortRef.current?.abort(); const controller = new AbortController(); abortRef.current = controller;
    loadingRef.current = true; setLoading(true); if (replace) setFilterLoading(true); setError("");
    try {
      const params = new URLSearchParams({ page: String(page), limit: "16" }); if (service !== "ALL") params.set("service", service);
      const response = await fetch(`/api/gallery-images?${params}`, { signal: controller.signal }); const result = await response.json() as PublicResponse;
      if (!response.ok) throw new Error(result.message || "The gallery could not be loaded."); if (requestId !== requestRef.current) return null;
      setItems((current) => { const source = replace ? [] : current; const ids = new Set(source.map((item) => item.id)); return [...source, ...result.images.filter((item) => !ids.has(item.id))]; });
      setPageInfo(result.pagination); return result.images;
    } catch (caught) { if ((caught as Error).name !== "AbortError" && requestId === requestRef.current) setError((caught as Error).message); return null; }
    finally { if (requestId === requestRef.current) { loadingRef.current = false; setLoading(false); setFilterLoading(false); } }
  }, []);
  const loadMore = useCallback(() => { if (!loadingRef.current && pageInfo.hasMore) void fetchPage(pageInfo.page + 1, filter); }, [fetchPage, filter, pageInfo.hasMore, pageInfo.page]);
  useEffect(() => () => abortRef.current?.abort(), []);
  useEffect(() => { const sentinel = sentinelRef.current; if (!sentinel || !pageInfo.hasMore) return; const observer = new IntersectionObserver((entries) => { if (entries[0]?.isIntersecting) loadMore(); }, { rootMargin: "500px 0px" }); observer.observe(sentinel); return () => observer.disconnect(); }, [loadMore, pageInfo.hasMore]);
  const chooseFilter = (next: Filter) => { if (next === filter) return; setFilter(next); setSelectedId(null); setItems([]); setPageInfo({ page: 1, limit: 16, total: 0, totalPages: 1, hasMore: false }); void fetchPage(1, next, true); };
  const close = useCallback(() => { setSelectedId(null); window.requestAnimationFrame(() => openerRef.current?.focus()); }, []);
  const previous = useCallback(() => { if (selectedIndex > 0) setSelectedId(items[selectedIndex - 1].id); }, [items, selectedIndex]);
  const next = useCallback(async () => { if (selectedIndex < 0) return; if (selectedIndex < items.length - 1) return setSelectedId(items[selectedIndex + 1].id); if (pageInfo.hasMore) { const nextItems = await fetchPage(pageInfo.page + 1, filter); if (nextItems?.[0]) setSelectedId(nextItems[0].id); } }, [fetchPage, filter, items, pageInfo.hasMore, pageInfo.page, selectedIndex]);
  const selected = selectedIndex >= 0 ? items[selectedIndex] : null;

  return <>
    <section id="gallery" aria-labelledby="gallery-heading" className="bg-[var(--brand-ivory)] px-3 py-10 sm:px-5 sm:py-14 lg:px-8"><div className="mx-auto max-w-[var(--site-width)] rounded-[28px] border border-white/75 bg-[#eee6da] p-4 shadow-[0_10px_26px_rgba(70,50,30,0.07),inset_1px_1px_2px_rgba(255,255,255,0.82)] sm:p-6 lg:rounded-[36px]">
      <header className="grid gap-5 border-b border-[var(--brand-navy)]/[0.08] pb-6 lg:grid-cols-[1fr_440px] lg:items-end"><div><p className="flex items-center gap-2 font-brand-sans text-[11px] font-bold uppercase tracking-[0.2em] text-[var(--brand-gold-700)]"><span className="h-px w-7 bg-[var(--brand-gold)]" /> Our work</p><h2 id="gallery-heading" className="mt-3 max-w-[650px] font-brand-display text-[34px] font-bold leading-[.98] tracking-[-.04em] text-[var(--brand-navy)] sm:text-[45px]">Crafted spaces.<br />Made to inspire<span className="text-[var(--brand-gold)]">.</span></h2></div><p className="font-brand-sans text-[13px] font-semibold leading-7 text-[var(--brand-text-muted)] lg:text-right">Explore a curated library of bespoke upholstery, commercial seating, interiors and carefully restored pieces.</p></header>
      <div className="flex flex-wrap gap-2 py-5" role="group" aria-label="Filter gallery by service">{filters.map((item) => <button key={item.value} type="button" aria-pressed={filter === item.value} onClick={() => chooseFilter(item.value)} disabled={filterLoading} className={`rounded-full border px-3.5 py-2 font-brand-sans text-[11px] font-bold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--brand-gold)] disabled:opacity-60 ${filter === item.value ? "border-[var(--brand-navy)] bg-[var(--brand-navy)] text-white" : "border-black/10 bg-white/45 text-[var(--brand-navy)] hover:bg-white/75"}`}>{item.label}</button>)}</div>
      <p className="sr-only" aria-live="polite">{loading ? "Loading gallery images" : `${items.length} of ${pageInfo.total} images shown`}</p>
      {filterLoading ? <GallerySkeleton /> : items.length ? <div className="columns-1 gap-3 sm:columns-2 lg:columns-3 xl:columns-4">{items.map((item) => <button key={item.id} type="button" onClick={(event) => { openerRef.current = event.currentTarget; setSelectedId(item.id); }} className="group relative mb-3 block w-full break-inside-avoid overflow-hidden rounded-[18px] bg-[var(--brand-navy)] text-left shadow-[0_4px_16px_rgba(20,31,45,.1)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--brand-gold)] focus-visible:ring-offset-2"><Image src={item.url} alt={item.alt} width={item.width || 1000} height={item.height || 850} sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 25vw" className="h-auto w-full object-cover transition duration-500 group-hover:scale-[1.02] motion-reduce:transition-none" /><span className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#08111e]/95 via-[#08111e]/45 to-transparent px-4 pb-4 pt-16 text-white"><span className="flex items-center justify-between gap-3"><span className="font-brand-sans text-[10px] font-bold uppercase tracking-[.15em] text-[#e0bd78]">No. {item.code} · {serviceLabel[item.service]}</span><Expand size={14} /></span></span></button>)}</div> : !error && <EmptyState filter={filter} onReset={() => chooseFilter("ALL")} />}
      {pageInfo.hasMore && !filterLoading && <div ref={sentinelRef} className="flex min-h-28 flex-col items-center justify-center gap-3 pt-7"><button type="button" onClick={loadMore} disabled={loading} className="flex min-h-11 items-center gap-2 rounded-xl bg-[var(--brand-navy)] px-6 font-brand-sans text-[11px] font-bold text-white shadow-lg shadow-[#101b2b]/10 transition hover:-translate-y-0.5 disabled:translate-y-0 disabled:opacity-60 motion-reduce:transition-none">{loading ? <LoaderCircle size={15} className="animate-spin motion-reduce:animate-none" /> : <Images size={15} />}{loading ? "Loading more work…" : "Load more work"}</button><span className="font-brand-sans text-[10px] font-bold uppercase tracking-[.12em] text-[var(--brand-text-muted)]">Showing {items.length} of {pageInfo.total}</span></div>}
      {!pageInfo.hasMore && items.length > 0 && <p className="pt-7 text-center font-brand-sans text-[10px] font-bold uppercase tracking-[.16em] text-[var(--brand-text-muted)]">You’ve reached the end · {pageInfo.total} pieces</p>}
      {error && <div role="alert" className="mt-5 flex flex-col items-center gap-3 rounded-2xl border border-red-200 bg-red-50/70 p-5 text-center"><p className="font-brand-sans text-[12px] font-semibold text-red-800">{error}</p><button type="button" onClick={() => pageInfo.page === 1 ? void fetchPage(1, filter, true) : loadMore()} className="flex items-center gap-2 rounded-lg bg-[var(--brand-navy)] px-4 py-2 font-brand-sans text-[11px] font-bold text-white"><RotateCcw size={13} /> Try again</button></div>}
    </div></section>
    {selected && <Lightbox key={selected.id} item={selected} count={items.length} index={selectedIndex} canNext={selectedIndex < items.length - 1 || pageInfo.hasMore} loadingMore={loading} onClose={close} onNext={() => void next()} onPrevious={previous} />}
  </>;
}

function GallerySkeleton() { return <div className="columns-1 gap-3 sm:columns-2 lg:columns-3 xl:columns-4" aria-hidden>{Array.from({ length: 8 }).map((_, index) => <div key={index} className={`mb-3 break-inside-avoid animate-pulse rounded-[18px] bg-[var(--brand-navy)]/10 motion-reduce:animate-none ${index % 3 === 0 ? "h-80" : "h-56"}`} />)}</div>; }
function EmptyState({ filter, onReset }: { filter: Filter; onReset: () => void }) { return <div className="flex min-h-[280px] flex-col items-center justify-center rounded-[22px] border border-dashed border-[var(--brand-navy)]/15 bg-white/30 px-5 text-center"><Images className="text-[var(--brand-gold-700)]" size={28} /><h3 className="mt-4 font-brand-display text-2xl font-bold text-[var(--brand-navy)]">The collection is being curated</h3><p className="mt-2 font-brand-sans text-[13px] font-semibold text-[var(--brand-text-muted)]">New work will appear here as soon as it is published.</p>{filter !== "ALL" && <button type="button" onClick={onReset} className="mt-4 rounded-lg bg-[var(--brand-navy)] px-4 py-2 font-brand-sans text-[11px] font-bold text-white">View all work</button>}</div>; }

function Lightbox({ item, count, index, canNext, loadingMore, onClose, onNext, onPrevious }: { item: PublicItem; count: number; index: number; canNext: boolean; loadingMore: boolean; onClose: () => void; onNext: () => void; onPrevious: () => void }) {
  const closeRef = useRef<HTMLButtonElement>(null); const dialogRef = useRef<HTMLDivElement>(null); const pointerRef = useRef<{ x: number; y: number; id: number } | null>(null); const [imageLoading, setImageLoading] = useState(true);
  useEffect(() => { closeRef.current?.focus(); const overflow = document.body.style.overflow; document.body.style.overflow = "hidden"; const keydown = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); else if (event.key === "ArrowRight" && canNext) onNext(); else if (event.key === "ArrowLeft" && index > 0) onPrevious(); if (event.key !== "Tab" || !dialogRef.current) return; const controls = Array.from(dialogRef.current.querySelectorAll<HTMLElement>("button:not([disabled])")); if (!controls.length) return; const first = controls[0], last = controls[controls.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; window.addEventListener("keydown", keydown); return () => { document.body.style.overflow = overflow; window.removeEventListener("keydown", keydown); }; }, [canNext, index, onClose, onNext, onPrevious]);
  const pointerDown = (event: ReactPointerEvent<HTMLDivElement>) => { if (event.pointerType === "mouse" && event.button !== 0) return; pointerRef.current = { x: event.clientX, y: event.clientY, id: event.pointerId }; event.currentTarget.setPointerCapture(event.pointerId); };
  const pointerUp = (event: ReactPointerEvent<HTMLDivElement>) => { const start = pointerRef.current; pointerRef.current = null; if (!start || start.id !== event.pointerId) return; const x = event.clientX - start.x, y = event.clientY - start.y; if (Math.abs(x) < 55 || Math.abs(x) <= Math.abs(y) * 1.2) return; if (x < 0 && canNext) onNext(); else if (x > 0 && index > 0) onPrevious(); };
  return createPortal(<div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="gallery-viewer-title" className="fixed inset-0 z-[4000] flex flex-col bg-[#030812]/[.98] text-white" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><header className="relative z-10 flex h-16 shrink-0 items-center justify-between gap-3 border-b border-white/10 bg-[#07111e]/85 px-3 backdrop-blur-md sm:px-6"><div className="min-w-0"><h2 id="gallery-viewer-title" className="truncate font-brand-sans text-[10px] font-bold uppercase tracking-[.18em] text-[#e0bd78]">No. {item.code} · {serviceLabel[item.service]}</h2><p className="mt-1 font-brand-sans text-[10px] font-semibold text-white/55">Original WebP · {index + 1} of {count}{loadingMore ? " · loading next" : ""}</p></div><button ref={closeRef} type="button" onClick={onClose} aria-label="Close image viewer" className="grid h-11 w-11 place-items-center rounded-lg border border-white/15 bg-white/[.07] hover:bg-white/15 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#e0bd78]"><X size={20} /></button></header>
    <div className="relative min-h-0 flex-1 touch-pan-y select-none" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }} onPointerDown={pointerDown} onPointerUp={pointerUp} onPointerCancel={() => { pointerRef.current = null; }}>{imageLoading && <span className="pointer-events-none absolute inset-0 z-10 grid place-items-center" aria-label="Loading full-quality image"><LoaderCircle className="animate-spin text-[#e0bd78] motion-reduce:animate-none" /></span>}<div className="pointer-events-none absolute inset-0 flex items-center justify-center p-2 sm:p-5"><Image src={item.url} alt={item.alt} width={item.width || 1600} height={item.height || 1200} unoptimized priority draggable={false} sizes="100vw" onLoad={() => setImageLoading(false)} className={`pointer-events-auto h-auto max-h-full w-auto max-w-full object-contain transition-opacity duration-300 motion-reduce:transition-none ${imageLoading ? "opacity-0" : "opacity-100"}`} /></div><button type="button" onClick={onPrevious} disabled={index === 0} aria-label="Previous image" className="absolute left-2 top-1/2 z-20 hidden h-16 w-12 -translate-y-1/2 place-items-center rounded-xl border border-white/10 bg-black/40 backdrop-blur hover:bg-black/65 disabled:opacity-20 sm:grid"><ChevronLeft size={27} /></button><button type="button" onClick={onNext} disabled={!canNext || loadingMore} aria-label="Next image" className="absolute right-2 top-1/2 z-20 hidden h-16 w-12 -translate-y-1/2 place-items-center rounded-xl border border-white/10 bg-black/40 backdrop-blur hover:bg-black/65 disabled:opacity-20 sm:grid">{loadingMore ? <LoaderCircle size={20} className="animate-spin" /> : <ChevronRight size={27} />}</button></div>
    <footer className="relative z-10 flex min-h-16 shrink-0 items-center justify-between gap-4 border-t border-white/10 bg-[#07111e]/85 px-4 py-3 backdrop-blur-md sm:px-6"><p className="line-clamp-2 max-w-3xl font-brand-sans text-[11px] font-semibold leading-5 text-white/70">{item.description}</p><span className="shrink-0 rounded-md border border-[#e0bd78]/35 bg-[#e0bd78]/10 px-2 py-1 font-brand-sans text-[9px] font-bold uppercase tracking-[.12em] text-[#e0bd78]">Original WebP</span></footer></div>, document.body);
}
