"use client";

import { ExternalLink, ImagePlus, Images, Pencil, RefreshCw, Search, Trash2 } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Spinner } from "@/components/lead-capture/ClayFormControls";
import { useToast } from "@/components/ui/ToastProvider";
import AdminGalleryModal, { type GalleryImage } from "./AdminGalleryModal";
import { ConfirmModal, fetchAdminJson, formatDateTime, formatFileSize, type ProjectService } from "./adminShared";

type Pagination = { page: number; limit: number; total: number; totalPages: number; hasMore: boolean };
type Response = { ok: true; images: GalleryImage[]; pagination: Pagination; counts: { all: number; active: number; inactive: number } };
type Detail = { ok: true; image: GalleryImage };
const serviceOptions: { value: ProjectService; label: string }[] = [{ value: "BESPOKE_SOFA", label: "Bespoke sofa" }, { value: "COMMERCIAL_SOFA", label: "Commercial sofa" }, { value: "INTERIOR_DESIGN", label: "Interior design" }, { value: "SOFA_REPAIR_RESTORATION", label: "Repair & restoration" }];

export default function AdminGallery() {
  const toast = useToast(); const addRef = useRef<HTMLButtonElement>(null); const editRef = useRef<HTMLButtonElement>(null);
  const [images, setImages] = useState<GalleryImage[]>([]); const [counts, setCounts] = useState({ all: 0, active: 0, inactive: 0 });
  const [pagination, setPagination] = useState<Pagination>({ page: 1, limit: 12, total: 0, totalPages: 1, hasMore: false });
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [service, setService] = useState<"" | ProjectService>(""); const [status, setStatus] = useState<"" | "true" | "false">("");
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [updatingId, setUpdatingId] = useState(""); const [deleteLoading, setDeleteLoading] = useState(false);
  const [editorOpen, setEditorOpen] = useState(false); const [editing, setEditing] = useState<GalleryImage | null>(null); const [deleting, setDeleting] = useState<GalleryImage | null>(null);
  const requestRef = useRef(0);
  const query = useMemo(() => { const params = new URLSearchParams({ page: String(page), limit: "12" }); if (search.trim()) params.set("search", search.trim()); if (service) params.set("service", service); if (status) params.set("active", status); return params.toString(); }, [page, search, service, status]);
  const load = useCallback(async () => { const id = ++requestRef.current; setLoading(true); setError(""); try { const result = await fetchAdminJson<Response>(`/api/admin/gallery-images?${query}`); if (id !== requestRef.current) return; setImages(result.images); setCounts(result.counts); setPagination(result.pagination); if (result.pagination.total > 0 && page > result.pagination.totalPages) setPage(result.pagination.totalPages); } catch (caught) { if (id === requestRef.current) setError((caught as Error).message || "Gallery library could not be loaded."); } finally { if (id === requestRef.current) setLoading(false); } }, [page, query]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 180); return () => window.clearTimeout(timer); }, [load]);
  function openCreate() { setEditing(null); setEditorOpen(true); }
  function openEdit(image: GalleryImage, button: HTMLButtonElement) { editRef.current = button; setEditing(image); setEditorOpen(true); }
  async function toggle(image: GalleryImage) { if (updatingId || deleteLoading) return; setUpdatingId(image.id); try { const result = await fetchAdminJson<Detail>(`/api/admin/gallery-images/${image.id}`, { method: "PATCH", body: JSON.stringify({ active: !image.active }) }); toast.success(result.image.active ? "Image activated." : "Image deactivated."); await load(); } catch (caught) { toast.error("Status could not be changed.", (caught as Error).message); } finally { setUpdatingId(""); } }
  async function remove() { if (!deleting || deleteLoading) return; const target = deleting; setDeleteLoading(true); try { const result = await fetchAdminJson<{ ok: true; cleanupWarning?: string }>(`/api/admin/gallery-images/${target.id}`, { method: "DELETE" }); toast.success("Gallery image deleted.", result.cleanupWarning || "The record and owned upload were removed."); setDeleting(null); if (images.length === 1 && page > 1) setPage((current) => current - 1); else await load(); } catch (caught) { toast.error("Image could not be deleted.", (caught as Error).message); } finally { setDeleteLoading(false); } }
  const busy = loading || Boolean(updatingId) || deleteLoading;
  return <div className="space-y-3">
    <header className="flex flex-col gap-3 rounded-xl border border-white/70 bg-white/50 p-3 shadow-[0_1px_3px_rgba(0,0,0,.04)] sm:flex-row sm:items-center sm:justify-between sm:p-4"><div><p className="font-brand-sans text-[10px] font-bold uppercase tracking-[.18em] text-[var(--brand-gold-700)]">Media library</p><h2 className="mt-1 font-brand-sans text-[16px] font-bold text-[var(--brand-navy)]">Gallery asset studio</h2><div className="mt-2 flex flex-wrap gap-2 font-brand-sans text-[11px] font-bold"><Stat label="Total" value={counts.all} /><Stat label="Active" value={counts.active} active /><Stat label="Inactive" value={counts.inactive} /></div></div><div className="flex gap-2"><a href="/gallery" target="_blank" rel="noreferrer" className="flex min-h-10 items-center justify-center gap-2 rounded-lg border border-black/[.08] bg-white/60 px-3 font-brand-sans text-[11px] font-bold text-[var(--brand-navy)] hover:bg-white"><ExternalLink size={13} /> View gallery</a><button ref={addRef} type="button" onClick={openCreate} disabled={busy} className="flex min-h-10 items-center justify-center gap-2 rounded-lg bg-[var(--brand-navy)] px-4 font-brand-sans text-[11px] font-bold text-white disabled:opacity-50"><ImagePlus size={15} /> Add image</button></div></header>
    <section className="min-w-0 rounded-xl border border-white/70 bg-white/50 p-3 shadow-[0_1px_3px_rgba(0,0,0,.04)] sm:p-4"><div className="grid gap-2 border-b border-black/[.06] pb-3 md:grid-cols-[1fr_180px_150px_auto]"><label className="relative"><span className="sr-only">Search gallery images</span><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--brand-text-muted)]" /><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Search code or description" className="h-9 w-full rounded-lg border border-white/70 bg-white/65 pl-9 pr-3 font-brand-sans text-[11px] outline-none focus:ring-2 focus:ring-[var(--brand-gold)]" /></label><select aria-label="Filter gallery by service" value={service} onChange={(event) => { setService(event.target.value as "" | ProjectService); setPage(1); }} className="h-9 rounded-lg border border-white/70 bg-white/65 px-2.5 font-brand-sans text-[11px] font-bold"><option value="">All services</option>{serviceOptions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><select aria-label="Filter gallery by visibility status" value={status} onChange={(event) => { setStatus(event.target.value as "" | "true" | "false"); setPage(1); }} className="h-9 rounded-lg border border-white/70 bg-white/65 px-2.5 font-brand-sans text-[11px] font-bold"><option value="">Any status</option><option value="true">Active</option><option value="false">Inactive</option></select><button type="button" onClick={() => void load()} disabled={loading} aria-label="Refresh gallery" className="grid h-9 w-9 place-items-center rounded-lg border border-white/70 bg-white/65 disabled:opacity-50"><RefreshCw size={14} className={loading ? "animate-spin motion-reduce:animate-none" : ""} /></button></div>
      {error && <div role="alert" className="mt-3 rounded-lg border border-red-200 bg-red-50 p-3 font-brand-sans text-[11px] font-semibold text-red-800">{error} <button type="button" onClick={() => void load()} className="ml-2 underline">Retry</button></div>}
      {loading ? <div className="grid gap-2 pt-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{Array.from({ length: 8 }).map((_, index) => <div key={index} className="h-56 animate-pulse rounded-xl bg-black/[.05] motion-reduce:animate-none" />)}</div> : images.length ? <div className="grid gap-2 pt-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{images.map((image) => { const updating = updatingId === image.id; return <article key={image.id} className="group overflow-hidden rounded-xl border border-black/[.06] bg-white/55"><div className="relative h-36 bg-[#eee6da] bg-contain bg-center bg-no-repeat" role="img" aria-label={image.alt} style={{ backgroundImage: `url("${image.url}")` }}><span className={`absolute left-2 top-2 rounded-md px-2 py-1 font-brand-sans text-[9px] font-bold uppercase ${image.active ? "bg-emerald-50 text-emerald-800" : "bg-slate-100 text-slate-600"}`}>{image.active ? "Active" : "Inactive"}</span><span className="absolute bottom-2 right-2 rounded-md bg-[#101b2b]/85 px-2 py-1 font-brand-sans text-[9px] font-bold text-white">No. {image.code}</span></div><div className="p-3"><p className="truncate font-brand-sans text-[11px] font-bold text-[var(--brand-navy)]">{image.alt}</p><p className="mt-1 line-clamp-2 min-h-8 font-brand-sans text-[10px] font-semibold leading-4 text-[var(--brand-text-muted)]">{image.description}</p><p className="mt-2 font-brand-sans text-[9px] font-bold uppercase text-[var(--brand-text-muted)]">{image.width && image.height ? `${image.width}×${image.height} · ` : ""}{image.storedBytes ? `${formatFileSize(image.storedBytes)} · ` : ""}{formatDateTime(image.updatedAt)}</p><div className="mt-3 grid grid-cols-[1fr_auto_auto] gap-1"><button type="button" onClick={() => void toggle(image)} disabled={busy} className="flex items-center justify-center gap-1.5 rounded-lg bg-[var(--brand-navy)]/[.06] px-2 py-2 font-brand-sans text-[10px] font-bold disabled:opacity-50">{updating && <Spinner />}{image.active ? "Deactivate" : "Activate"}</button><button type="button" onClick={(event) => openEdit(image, event.currentTarget)} disabled={busy} aria-label={`Edit image ${image.code}`} className="grid h-8 w-8 place-items-center rounded-lg hover:bg-black/5 disabled:opacity-50"><Pencil size={13} /></button><button type="button" onClick={() => setDeleting(image)} disabled={busy} aria-label={`Delete image ${image.code}`} className="grid h-8 w-8 place-items-center rounded-lg text-red-700 hover:bg-red-50 disabled:opacity-50"><Trash2 size={13} /></button></div></div></article>; })}</div> : <div className="grid min-h-[350px] place-items-center text-center"><div><Images size={24} className="mx-auto text-[var(--brand-gold-700)]" /><h3 className="mt-3 font-brand-sans text-[13px] font-bold">No gallery assets found</h3><p className="mt-1 font-brand-sans text-[11px] font-semibold text-[var(--brand-text-muted)]">Adjust the filters or upload the first image.</p></div></div>}
      {!loading && pagination.total > 0 && <AdminPagination pagination={pagination} disabled={busy} onPage={setPage} />}
    </section>
    {editorOpen && <AdminGalleryModal open image={editing} opener={editing ? editRef : addRef} onClose={() => setEditorOpen(false)} onSaved={() => { setEditorOpen(false); void load(); }} />}
    <ConfirmModal open={Boolean(deleting)} title="Permanently delete image?" message={deleting ? `Image ${deleting.code} will be removed from the library. Deactivation is safer if you may need it again.` : ""} confirmLabel="Delete permanently" danger loading={deleteLoading} onConfirm={() => void remove()} onCancel={() => !deleteLoading && setDeleting(null)} />
  </div>;
}

function AdminPagination({ pagination, disabled, onPage }: { pagination: Pagination; disabled: boolean; onPage: (page: number) => void }) { const pages = pageNumbers(pagination.page, pagination.totalPages); return <nav aria-label="Gallery pages" className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-black/[.06] pt-3"><p className="font-brand-sans text-[10px] font-bold uppercase tracking-[.1em] text-[var(--brand-text-muted)]">Page {pagination.page} of {pagination.totalPages} · {pagination.total} assets</p><div className="flex items-center gap-1"><button type="button" disabled={disabled || pagination.page <= 1} onClick={() => onPage(pagination.page - 1)} className="h-9 rounded-lg border border-black/10 bg-white/60 px-3 font-brand-sans text-[10px] font-bold disabled:opacity-40">Previous</button>{pages.map((value, index) => value === "…" ? <span key={`e-${index}`} className="grid h-9 w-7 place-items-center text-xs text-[var(--brand-text-muted)]">…</span> : <button key={value} type="button" aria-current={value === pagination.page ? "page" : undefined} disabled={disabled} onClick={() => onPage(value)} className={`h-9 min-w-9 rounded-lg px-2 font-brand-sans text-[10px] font-bold ${value === pagination.page ? "bg-[var(--brand-navy)] text-white" : "border border-black/10 bg-white/60"}`}>{value}</button>)}<button type="button" disabled={disabled || pagination.page >= pagination.totalPages} onClick={() => onPage(pagination.page + 1)} className="h-9 rounded-lg border border-black/10 bg-white/60 px-3 font-brand-sans text-[10px] font-bold disabled:opacity-40">Next</button></div></nav>; }
function pageNumbers(page: number, total: number): (number | "…")[] { if (total <= 7) return Array.from({ length: total }, (_, index) => index + 1); const values: (number | "…")[] = [1]; if (page > 4) values.push("…"); for (let value = Math.max(2, page - 1); value <= Math.min(total - 1, page + 1); value++) values.push(value); if (page < total - 3) values.push("…"); values.push(total); return values; }
function Stat({ label, value, active = false }: { label: string; value: number; active?: boolean }) { return <span className={`rounded-md px-2 py-1 ${active ? "bg-emerald-50 text-emerald-800" : "bg-[var(--brand-navy)]/[.06] text-[var(--brand-navy)]"}`}>{label} {value}</span>; }
