"use client";

import { Check, ImagePlus, ShieldCheck, UploadCloud, X } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { Spinner } from "@/components/lead-capture/ClayFormControls";
import { useToast } from "@/components/ui/ToastProvider";
import { AdminTextField, AdminTextareaField, fetchAdminJson, formatFileSize, makeApiError, type ApiError, type ProjectService } from "./adminShared";

export type GalleryImage = { id: string; url: string; storageKey?: string; alt: string; description: string; code: number; service: ProjectService; active: boolean; sortOrder: number; width?: number; height?: number; mimeType?: string; storedBytes?: number; originalBytes?: number; createdAt: string; updatedAt: string };
type UploadReceipt = { ok: true; url: string; storageKey: string; mimeType: "image/webp"; width: number; height: number; originalBytes: number; storedBytes: number; savingsPercent: number; qualityPreserved: true };
type Detail = { ok: true; image: GalleryImage; cleanupWarning?: string };
type FormState = { id: string; url: string; storageKey: string; alt: string; description: string; code: string; service: ProjectService; active: boolean; sortOrder: number; width?: number; height?: number; mimeType?: string; storedBytes?: number; originalBytes?: number; savingsPercent?: number };
const services: { value: ProjectService; label: string }[] = [{ value: "BESPOKE_SOFA", label: "Bespoke sofa" }, { value: "COMMERCIAL_SOFA", label: "Commercial sofa" }, { value: "INTERIOR_DESIGN", label: "Interior design" }, { value: "SOFA_REPAIR_RESTORATION", label: "Repair & restoration" }];
const empty: FormState = { id: "", url: "", storageKey: "", alt: "", description: "", code: "", service: "BESPOKE_SOFA", active: true, sortOrder: 0 };

export default function AdminGalleryModal({ open, image, opener, onClose, onSaved }: { open: boolean; image: GalleryImage | null; opener: React.RefObject<HTMLButtonElement | null>; onClose: () => void; onSaved: (image: GalleryImage) => void }) {
  const toast = useToast(); const dialogRef = useRef<HTMLDivElement>(null); const inputRef = useRef<HTMLInputElement>(null); const titleRef = useRef<HTMLHeadingElement>(null);
  const stagedRef = useRef(""); const busyRef = useRef(false); const [form, setForm] = useState<FormState>(() => image ? { id: image.id, url: image.url, storageKey: image.storageKey || "", alt: image.alt, description: image.description, code: String(image.code), service: image.service, active: image.active, sortOrder: image.sortOrder, width: image.width, height: image.height, mimeType: image.mimeType, storedBytes: image.storedBytes, originalBytes: image.originalBytes } : empty); const [uploading, setUploading] = useState(false); const [saving, setSaving] = useState(false); const [progress, setProgress] = useState(0); const [dragging, setDragging] = useState(false); const [fieldError, setFieldError] = useState("");
  const discard = useCallback(async (key: string, quiet = false) => { if (!key) return; try { await fetchAdminJson("/api/admin/gallery-images/discard", { method: "POST", body: JSON.stringify({ storageKey: key }) }); } catch (error) { if (!quiet) toast.error("Unused upload could not be removed.", (error as Error).message); } }, [toast]);
  useEffect(() => { if (!open) return; window.requestAnimationFrame(() => titleRef.current?.focus()); }, [open]);
  useEffect(() => { if (!open) return; const overflow = document.body.style.overflow; document.body.style.overflow = "hidden"; const keydown = (event: KeyboardEvent) => { if (event.key === "Escape" && !busyRef.current) close(); if (event.key !== "Tab" || !dialogRef.current) return; const controls = Array.from(dialogRef.current.querySelectorAll<HTMLElement>("button:not([disabled]),input:not([disabled]),textarea:not([disabled]),select:not([disabled]),[tabindex='0']")); if (!controls.length) return; const first = controls[0], last = controls[controls.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; window.addEventListener("keydown", keydown); return () => { document.body.style.overflow = overflow; window.removeEventListener("keydown", keydown); }; });
  useEffect(() => () => { const key = stagedRef.current; if (key) void fetch("/api/admin/gallery-images/discard", { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ storageKey: key }), keepalive: true }).catch(() => undefined); }, []);

  function close() { if (busyRef.current) return; const staged = stagedRef.current; stagedRef.current = ""; if (staged) void discard(staged); onClose(); window.requestAnimationFrame(() => opener.current?.focus()); }
  function upload(file: File) { if (busyRef.current) return; busyRef.current = true; setUploading(true); setProgress(1); setFieldError(""); const xhr = new XMLHttpRequest(), body = new FormData(); body.append("file", file); xhr.open("POST", "/api/admin/gallery-images/upload"); xhr.withCredentials = true; xhr.upload.onprogress = (event) => event.lengthComputable && setProgress(Math.max(1, Math.round(event.loaded / event.total * 90))); xhr.onload = () => { let response: unknown; try { response = JSON.parse(xhr.responseText); } catch { response = null; } if (xhr.status >= 200 && xhr.status < 300 && response) { const receipt = response as UploadReceipt; const old = stagedRef.current; stagedRef.current = receipt.storageKey; setForm((current) => ({ ...current, url: receipt.url, storageKey: receipt.storageKey, mimeType: receipt.mimeType, width: receipt.width, height: receipt.height, originalBytes: receipt.originalBytes, storedBytes: receipt.storedBytes, savingsPercent: receipt.savingsPercent, alt: current.alt || file.name.replace(/\.[^.]+$/, "").replace(/[-_]+/g, " ") })); if (old && old !== receipt.storageKey) void discard(old, true); setProgress(100); toast.success("WebP prepared.", "A lossless, full-quality WebP is ready to publish."); } else { const api = response as { message?: string }; toast.error("Upload failed.", api?.message || "Choose another image."); } busyRef.current = false; setUploading(false); }; xhr.onerror = () => { busyRef.current = false; setUploading(false); toast.error("Upload failed.", makeApiError("Could not reach the upload service.").message); }; xhr.send(body); }
  async function save() { if (busyRef.current) return; busyRef.current = true; setSaving(true); setFieldError(""); try { const path = form.id ? `/api/admin/gallery-images/${form.id}` : "/api/admin/gallery-images"; const result = await fetchAdminJson<Detail>(path, { method: form.id ? "PATCH" : "POST", body: JSON.stringify({ ...form, id: undefined, savingsPercent: undefined }) }); stagedRef.current = ""; toast.success(form.id ? "Gallery image updated." : "Gallery image published.", result.cleanupWarning || `Image ${result.image.code} is saved.`); onSaved(result.image); onClose(); window.requestAnimationFrame(() => opener.current?.focus()); } catch (caught) { const api = caught as ApiError; const message = api.fieldErrors ? Object.values(api.fieldErrors).join(" ") : api.message; setFieldError(message); toast.error("Image could not be saved.", message); } finally { busyRef.current = false; setSaving(false); } }
  if (!open) return null;
  return <div className="fixed inset-0 z-[5000] flex items-end justify-center bg-[#08111e]/75 p-0 backdrop-blur-sm sm:items-center sm:p-5" onMouseDown={(event) => { if (event.target === event.currentTarget && !busyRef.current) close(); }}><div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="gallery-editor-title" aria-describedby="gallery-editor-description" className="flex h-[100dvh] w-full max-w-5xl flex-col overflow-hidden bg-[#f2ebe0] shadow-[0_30px_100px_rgba(0,0,0,.45)] sm:h-auto sm:max-h-[calc(100dvh-2.5rem)] sm:rounded-2xl sm:border sm:border-white/80">
    <header className="flex shrink-0 items-center justify-between border-b border-black/[.07] px-4 py-3 sm:px-6"><div><p className="font-brand-sans text-[9px] font-bold uppercase tracking-[.18em] text-[var(--brand-gold-700)]">Asset editor</p><h2 ref={titleRef} tabIndex={0} id="gallery-editor-title" className="mt-1 font-brand-sans text-lg font-bold text-[var(--brand-navy)] outline-none focus-visible:ring-2 focus-visible:ring-[var(--brand-gold)]">{image ? `Edit image ${image.code}` : "Add gallery image"}</h2><p id="gallery-editor-description" className="mt-0.5 font-brand-sans text-[11px] font-semibold text-[var(--brand-text-muted)]">Upload a full-quality WebP and complete its public details.</p></div><button type="button" onClick={close} disabled={uploading || saving} aria-label="Close asset editor" className="grid h-10 w-10 place-items-center rounded-lg hover:bg-black/5 disabled:opacity-40"><X size={18} /></button></header>
    <div className="grid min-h-0 flex-1 overflow-y-auto lg:grid-cols-[1.15fr_.85fr]"><div className="border-b border-black/[.07] p-4 lg:border-b-0 lg:border-r lg:p-6"><input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ""; if (file) upload(file); }} /><button type="button" disabled={uploading || saving} onClick={() => inputRef.current?.click()} onDragOver={(event) => { event.preventDefault(); if (!busyRef.current) setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(event) => { event.preventDefault(); setDragging(false); const file = event.dataTransfer.files[0]; if (file) upload(file); }} className={`relative aspect-[4/3] w-full overflow-hidden rounded-xl border border-dashed bg-[#e7ded0] ${dragging ? "border-[var(--brand-gold)] ring-2 ring-[var(--brand-gold)]/20" : "border-[var(--brand-navy)]/20"}`}>{form.url ? <span role="img" aria-label={form.alt || "Gallery preview"} className="absolute inset-0 bg-contain bg-center bg-no-repeat" style={{ backgroundImage: `url("${form.url}")` }} /> : <span className="absolute inset-0 grid place-items-center text-center"><span><UploadCloud size={32} className="mx-auto text-[var(--brand-gold-700)]" /><span className="mt-3 block font-brand-sans text-[12px] font-bold">Drop an image or choose a file</span><span className="mt-1 block font-brand-sans text-[11px] font-semibold text-[var(--brand-text-muted)]">JPG, PNG or WebP · up to 9MB</span></span></span>}{uploading && <span className="absolute inset-x-3 bottom-3 rounded-lg bg-[#101b2b]/90 p-3 text-left text-white"><span className="flex justify-between font-brand-sans text-[10px] font-bold"><span>Creating lossless WebP</span><span>{progress}%</span></span><span className="mt-2 block h-1 overflow-hidden rounded bg-white/20"><span className="block h-full bg-[var(--brand-gold)]" style={{ width: `${progress}%` }} /></span></span>}</button>{form.storedBytes && <div className="mt-3 flex gap-2 rounded-xl border border-emerald-200 bg-emerald-50/80 p-3"><ShieldCheck size={17} className="shrink-0 text-emerald-700" /><div><p className="font-brand-sans text-[11px] font-bold text-emerald-900">Original quality · lossless WebP</p><p className="mt-1 font-brand-sans text-[10px] font-semibold text-emerald-800">{form.width}×{form.height} · {formatFileSize(form.storedBytes)} stored{form.originalBytes ? ` · source ${formatFileSize(form.originalBytes)}` : ""}</p></div></div>}</div>
      <div className="grid content-start gap-3 p-4 sm:p-6"><div className="grid grid-cols-2 gap-3"><AdminTextField label="Image code" value={form.code} onChange={(value) => setForm({ ...form, code: value.replace(/\D/g, "").slice(0, 9) })} placeholder="2009" inputMode="numeric" /><label className="grid gap-1 font-brand-sans text-[11px] font-bold text-[var(--brand-navy)]">Service<select value={form.service} onChange={(event) => setForm({ ...form, service: event.target.value as ProjectService })} className="h-[40px] rounded-lg border border-white/70 bg-white/70 px-2.5 text-[11px] outline-none focus:ring-2 focus:ring-[var(--brand-gold)]">{services.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label></div><AdminTextField label="Alt text" value={form.alt} onChange={(value) => setForm({ ...form, alt: value })} placeholder="Describe what is visible" /><AdminTextareaField label="Description" value={form.description} onChange={(value) => setForm({ ...form, description: value })} placeholder="A useful editorial description of the work..." /><label className="flex items-center justify-between rounded-xl border border-white/70 bg-white/55 px-3 py-3 font-brand-sans text-[11px] font-bold"><span><span className="block">Visible in public gallery</span><span className="mt-0.5 block text-[10px] font-semibold text-[var(--brand-text-muted)]">Deactivate instead of deleting</span></span><input type="checkbox" checked={form.active} onChange={(event) => setForm({ ...form, active: event.target.checked })} className="h-4 w-4 accent-[var(--brand-navy)]" /></label>{fieldError && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 font-brand-sans text-[11px] font-semibold text-red-800">{fieldError}</p>}</div></div>
    <footer className="flex shrink-0 items-center justify-end gap-2 border-t border-black/[.07] bg-white/30 px-4 py-3 sm:px-6"><button type="button" onClick={close} disabled={uploading || saving} className="min-h-10 rounded-lg border border-black/10 bg-white/60 px-4 font-brand-sans text-[11px] font-bold disabled:opacity-50">Cancel</button><button type="button" onClick={() => void save()} disabled={uploading || saving} className="flex min-h-10 min-w-32 items-center justify-center gap-2 rounded-lg bg-[var(--brand-navy)] px-5 font-brand-sans text-[11px] font-bold text-white disabled:opacity-50">{saving ? <Spinner /> : image ? <Check size={14} /> : <ImagePlus size={14} />}{image ? "Save changes" : "Publish image"}</button></footer>
  </div></div>;
}
